"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";

type FleetStatus = "OPERATING" | "STOPPED" | "MAINTENANCE" | "WAITING_PART" | "WAITING_ORDER" | "WAITING_MECHANIC" | "WAITING_EXTERNAL_SERVICE" | "READY" | "INACTIVE";
type OrderStatus = "REQUESTED" | "QUOTING" | "ORDERED" | "WAITING_DELIVERY" | "RECEIVED" | "CANCELLED" | "CLOSED";
type FleetOrder = { id?:string; orderNumber:string; requestedAt:string; description:string; quantity:number|null; unit:string|null; requester:string|null; supplier:string|null; status:OrderStatus; statusLabel?:string; notes:string|null };
type FleetItem = {
  id:number; prefix:string; model:string; brand:string; category:string; front:string; registrationStatus:string;
  status:FleetStatus; statusLabel:string; sinceAt:string; occurrenceId:string|null; stoppedAt:string|null; endedAt:string|null; returnedToOperationAt:string|null;
  reason:string|null; problemDescription:string|null; serviceDescription:string|null; servicePerformed:string|null; location:string|null; updatedBy:string;
  mechanics:string[]; orders:FleetOrder[]; hasPendingOrder:boolean;
};
type Movement = { id:string; occurrenceId:string|null; equipmentId:number; prefix:string; model:string; front:string; category:string; previousStatus:FleetStatus; status:FleetStatus; statusLabel:string; occurredAt:string; reason:string|null; problemDescription:string|null; serviceDescription:string|null; servicePerformed:string|null; location:string|null; notes:string|null; mechanics:string[]; updatedBy:string };
type FleetResponse = {
  generatedAt:string; selectedDate:string;
  metrics:{ total:number; operating:number; stopped:number; maintenance:number; waitingPart:number; releasedToday:number };
  settings:{ attentionHours:number; highHours:number; criticalHours:number };
  mechanics:string[]; items:FleetItem[]; movements:Movement[];
};
type AuthUser = { name:string; permissions:string[] };
type DraftOrder = FleetOrder & { clientId:string };
type HistoryData = { equipment:{prefix:string;model:string;category:string;front:string}; occurrences:Array<{id:string;startedAt:string;endedAt:string|null;returnedToOperationAt:string|null;reason:string|null;problemDescription:string|null;servicePerformed:string|null;partsUsed:string|null;events:Movement[];orders:FleetOrder[]}>; standaloneEvents:Movement[] };

const statusOptions:Array<[FleetStatus,string]> = [
  ["OPERATING","OPERANDO"], ["STOPPED","PARADO"], ["MAINTENANCE","EM MANUTENÇÃO"], ["WAITING_PART","AGUARDANDO PEÇA"],
  ["WAITING_ORDER","AGUARDANDO PEDIDO"], ["WAITING_MECHANIC","AGUARDANDO MECÂNICO"], ["WAITING_EXTERNAL_SERVICE","AGUARDANDO SERVIÇO EXTERNO"],
  ["READY","LIBERADO / PRONTO"], ["INACTIVE","INATIVO"],
];
const orderOptions:Array<[OrderStatus,string]> = [["REQUESTED","SOLICITADO"],["QUOTING","EM COTAÇÃO"],["ORDERED","PEDIDO REALIZADO"],["WAITING_DELIVERY","AGUARDANDO ENTREGA"],["RECEIVED","RECEBIDO"],["CANCELLED","CANCELADO"],["CLOSED","ENCERRADO"]];
const emptyMetrics = { total:0, operating:0, stopped:0, maintenance:0, waitingPart:0, releasedToday:0 };
const emptyResponse:FleetResponse = { generatedAt:"", selectedDate:"", metrics:emptyMetrics, settings:{attentionHours:4,highHours:12,criticalHours:24}, mechanics:[], items:[], movements:[] };

async function api<T>(url:string, options?:RequestInit):Promise<T> { const response=await fetch(url,{cache:"no-store",...options}); const data=await response.json().catch(()=>({})); if(!response.ok)throw new Error(String(data.error??"A operação não pôde ser concluída.")); return data as T; }
function localDay(){return new Intl.DateTimeFormat("en-CA",{timeZone:"America/Fortaleza",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
function localDateTime(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Fortaleza",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const value=Object.fromEntries(parts.map((part)=>[part.type,part.value]));return `${value.year}-${value.month}-${value.day}T${value.hour}:${value.minute}`;}
function formatDate(value:string|null,withTime=true){if(!value)return "—";const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Fortaleza",dateStyle:"short",...(withTime?{timeStyle:"short" as const}:{})}).format(date);}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]/g,"");}
function hoursSince(value:string|null,now:number){if(!value)return 0;return Math.max(0,(now-new Date(value).getTime())/3_600_000);}
function duration(value:string|null,now:number){const hours=hoursSince(value,now);const days=Math.floor(hours/24);const fullHours=Math.floor(hours%24);const minutes=Math.floor(hours*60%60);return `${days?`${days}d `:""}${fullHours}h ${minutes}min`;}
function datetimeIso(value:string){const parsed=new Date(value);return Number.isNaN(parsed.getTime())?new Date().toISOString():parsed.toISOString();}
function tone(status:FleetStatus){return status==="OPERATING"?"operating":status==="READY"?"ready":status==="MAINTENANCE"?"maintenance":status==="WAITING_PART"||status==="WAITING_ORDER"?"waiting":status==="INACTIVE"?"inactive":"stopped";}
function priority(status:FleetStatus){return ({WAITING_PART:1,WAITING_ORDER:2,MAINTENANCE:3,STOPPED:4,WAITING_MECHANIC:5,WAITING_EXTERNAL_SERVICE:6,READY:7,INACTIVE:8,OPERATING:9} as Record<FleetStatus,number>)[status];}

export default function FleetStatusView({ authUser, flash }:{authUser:AuthUser;flash:(message:string)=>void}) {
  const [data,setData]=useState<FleetResponse>(emptyResponse); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  const [selectedDate,setSelectedDate]=useState(localDay()); const [now,setNow]=useState(0);
  const [query,setQuery]=useState(""); const [statusFilter,setStatusFilter]=useState(""); const [frontFilter,setFrontFilter]=useState(""); const [categoryFilter,setCategoryFilter]=useState(""); const [equipmentFilter,setEquipmentFilter]=useState(""); const [mechanicFilter,setMechanicFilter]=useState(""); const [pendingOnly,setPendingOnly]=useState(false); const [minimumHours,setMinimumHours]=useState("");
  const [editing,setEditing]=useState<FleetItem|null>(null); const [historyItem,setHistoryItem]=useState<FleetItem|null>(null); const [history,setHistory]=useState<HistoryData|null>(null); const [historyLoading,setHistoryLoading]=useState(false);
  const [settingsOpen,setSettingsOpen]=useState(false); const canUpdate=authUser.permissions.includes("fleet.update"); const canReport=authUser.permissions.includes("fleet.report");
  const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await api<FleetResponse>(`/api/fleet-status?date=${selectedDate}`));}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível carregar a frota.");}finally{setLoading(false);}},[selectedDate]);
  useEffect(()=>{load();},[load]); useEffect(()=>{const tick=()=>setNow(Date.now());const initial=window.setTimeout(tick,0);const timer=window.setInterval(tick,60_000);return()=>{window.clearTimeout(initial);window.clearInterval(timer);};},[]);
  const fronts=useMemo(()=>[...new Set(data.items.map((item)=>item.front))].sort((a,b)=>a.localeCompare(b,"pt-BR")),[data.items]);
  const categories=useMemo(()=>[...new Set(data.items.map((item)=>item.category))].sort((a,b)=>a.localeCompare(b,"pt-BR")),[data.items]);
  const filtered=useMemo(()=>data.items.filter((item)=>{
    const haystack=normalize(`${item.prefix} ${item.model} ${item.category} ${item.front}`); const needle=normalize(query);
    if(needle&&!haystack.includes(needle))return false;if(statusFilter&&item.status!==statusFilter)return false;if(frontFilter&&item.front!==frontFilter)return false;
    if(categoryFilter&&item.category!==categoryFilter)return false;if(equipmentFilter&&item.id!==Number(equipmentFilter))return false;if(mechanicFilter&&!item.mechanics.includes(mechanicFilter))return false;
    if(pendingOnly&&!item.hasPendingOrder)return false;if(minimumHours&&hoursSince(item.stoppedAt??item.sinceAt,now)<Number(minimumHours))return false;return true;
  }).sort((a,b)=>priority(a.status)-priority(b.status)||hoursSince(b.stoppedAt??b.sinceAt,now)-hoursSince(a.stoppedAt??a.sinceAt,now)||a.prefix.localeCompare(b.prefix,"pt-BR",{numeric:true})),[data.items,query,statusFilter,frontFilter,categoryFilter,equipmentFilter,mechanicFilter,pendingOnly,minimumHours,now]);
  const openHistory=async(item:FleetItem)=>{setHistoryItem(item);setHistory(null);setHistoryLoading(true);try{setHistory(await api<HistoryData>(`/api/fleet-status?equipmentId=${item.id}`));}catch(problem){flash(problem instanceof Error?problem.message:"Não foi possível abrir o histórico.");setHistoryItem(null);}finally{setHistoryLoading(false);}};
  const exportPdf=()=>{const params=new URLSearchParams({date:selectedDate});if(statusFilter)params.append("status",statusFilter);if(frontFilter)params.append("front",frontFilter);if(categoryFilter)params.append("category",categoryFilter);if(equipmentFilter)params.append("equipment",equipmentFilter);if(mechanicFilter)params.append("mechanic",mechanicFilter);window.open(`/api/fleet-status-report-pdf?${params.toString()}`,"_blank","noopener,noreferrer");};
  if(loading&&!data.generatedAt)return <div className="fleet-loading"><span/><p>Carregando situação operacional da frota...</p></div>;
  return <div className="fleet-module">
    <div className="fleet-heading"><div><p>PAINEL OPERACIONAL EM TEMPO REAL</p><h1>Status da Frota</h1><span>Status atual e histórico de ocorrências preservados separadamente da troca de óleo.</span></div><div className="fleet-heading-actions"><button className="fleet-secondary" onClick={()=>setSettingsOpen(!settingsOpen)} disabled={!canUpdate}>⚙ Limites</button><button className="fleet-pdf" onClick={exportPdf} disabled={!canReport}>⇩ EXPORTAR RELATÓRIO PDF</button></div></div>
    {error&&<div className="fleet-error"><strong>Falha ao carregar o módulo</strong><span>{error}</span><button onClick={load}>Tentar novamente</button></div>}
    {settingsOpen&&<FleetSettings settings={data.settings} close={()=>setSettingsOpen(false)} saved={async(message)=>{setSettingsOpen(false);await load();flash(message);}}/>}
    <div className="fleet-metrics">
      <FleetMetric icon="▦" label="TOTAL DA FROTA" value={data.metrics.total} tone="navy"/><FleetMetric icon="▶" label="OPERANDO" value={data.metrics.operating} tone="green"/>
      <FleetMetric icon="■" label="PARADOS" value={data.metrics.stopped} tone="red"/><FleetMetric icon="◆" label="EM MANUTENÇÃO" value={data.metrics.maintenance} tone="blue"/>
      <FleetMetric icon="⌛" label="AGUARDANDO PEÇA" value={data.metrics.waitingPart} tone="amber"/><FleetMetric icon="✓" label="LIBERADOS HOJE" value={data.metrics.releasedToday} tone="mint"/>
    </div>
    <div className="fleet-toolbar">
      <label className="fleet-search"><span>⌕</span><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Pesquisar equipamento..."/></label>
      <select value={statusFilter} onChange={(event)=>setStatusFilter(event.target.value)}><option value="">Todos os status</option>{statusOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>
      <select value={frontFilter} onChange={(event)=>setFrontFilter(event.target.value)}><option value="">Todas as frentes</option>{fronts.map((value)=><option key={value}>{value}</option>)}</select>
      <select value={categoryFilter} onChange={(event)=>setCategoryFilter(event.target.value)}><option value="">Todas as categorias</option>{categories.map((value)=><option key={value}>{value}</option>)}</select>
      <select value={equipmentFilter} onChange={(event)=>setEquipmentFilter(event.target.value)}><option value="">Todos os equipamentos</option>{data.items.map((item)=><option key={item.id} value={item.id}>{item.prefix}</option>)}</select>
      <select value={mechanicFilter} onChange={(event)=>setMechanicFilter(event.target.value)}><option value="">Todos os mecânicos</option>{data.mechanics.map((value)=><option key={value}>{value}</option>)}</select>
      <select value={minimumHours} onChange={(event)=>setMinimumHours(event.target.value)}><option value="">Qualquer tempo parado</option><option value="4">Mais de 4 horas</option><option value="12">Mais de 12 horas</option><option value="24">Mais de 24 horas</option><option value="72">Mais de 3 dias</option></select>
      <label className="fleet-check"><input type="checkbox" checked={pendingOnly} onChange={(event)=>setPendingOnly(event.target.checked)}/> Com pedido pendente</label>
    </div>
    <div className="fleet-table-wrap"><table className="fleet-table"><thead><tr><th>EQUIPAMENTO</th><th>STATUS ATUAL</th><th>DESDE / TEMPO</th><th>MOTIVO / SERVIÇO</th><th>RESPONSÁVEL</th><th>PEDIDO</th><th>AÇÕES</th></tr></thead><tbody>
      {filtered.map((item)=>{const stopped=item.status!=="OPERATING"&&item.status!=="INACTIVE";const hours=hoursSince(item.stoppedAt??item.sinceAt,now);const severity=hours>=data.settings.criticalHours?"critical":hours>=data.settings.highHours?"high":hours>=data.settings.attentionHours?"attention":"normal";return <tr key={item.id} className={`fleet-row ${stopped?severity:""}`}>
        <td><div className="fleet-equipment"><b>{item.prefix}</b><span>{item.model}</span><small>{item.category} · {item.front}</small></div></td>
        <td><span className={`fleet-status ${tone(item.status)}`}>{item.statusLabel}</span></td>
        <td><div className="fleet-time"><b>{formatDate(item.stoppedAt??item.sinceAt)}</b><span>{stopped?duration(item.stoppedAt??item.sinceAt,now):`Atualizado ${formatDate(item.sinceAt)}`}</span></div></td>
        <td><div className="fleet-description"><b>{item.reason??item.problemDescription??"Sem ocorrência ativa"}</b><span>{item.serviceDescription??item.servicePerformed??(item.status==="OPERATING"?"Equipamento disponível para operação":"Aguardando detalhamento")}</span></div></td>
        <td><div className="fleet-people"><b>{item.mechanics.join(", ")||"—"}</b><span>Atualizado por {item.updatedBy}</span></div></td>
        <td>{item.orders.length?<div className="fleet-order-cell"><b>{item.orders[0].orderNumber}</b><span>{item.orders[0].statusLabel}</span>{item.orders.length>1&&<small>+{item.orders.length-1} pedido(s)</small>}</div>:<span className="fleet-none">Nenhum</span>}</td>
        <td><div className="fleet-actions">{canUpdate&&<button onClick={()=>setEditing(item)}>ATUALIZAR STATUS</button>}<button className="history" onClick={()=>openHistory(item)}>VER HISTÓRICO</button></div></td>
      </tr>;})}
      {!filtered.length&&<tr><td colSpan={7}><div className="fleet-empty"><span>⌕</span><strong>Nenhum equipamento encontrado</strong><small>Ajuste a pesquisa ou os filtros.</small></div></td></tr>}
    </tbody></table></div>
    <section className="fleet-movements"><header><div><p>LINHA DO TEMPO</p><h2>Movimentações do dia</h2></div><label>Data<input type="date" value={selectedDate} onChange={(event)=>setSelectedDate(event.target.value)}/></label></header><div className="fleet-timeline">
      {data.movements.map((movement)=><article key={movement.id}><time>{new Intl.DateTimeFormat("pt-BR",{timeZone:"America/Fortaleza",hour:"2-digit",minute:"2-digit"}).format(new Date(movement.occurredAt))}</time><i className={tone(movement.status)}/><div><b>{movement.prefix} → {movement.statusLabel}</b><span>{movement.reason??movement.serviceDescription??movement.servicePerformed??"Atualização operacional"}</span><small>{movement.mechanics.length?`Mecânico(s): ${movement.mechanics.join(", ")} · `:""}Atualizado por {movement.updatedBy}</small></div></article>)}
      {!data.movements.length&&<div className="fleet-no-movements">Nenhuma movimentação registrada nesta data.</div>}
    </div></section>
    {editing&&<UpdateFleetModal item={editing} mechanics={data.mechanics} close={()=>setEditing(null)} saved={async(message)=>{setEditing(null);await load();flash(message);}}/>}
    {historyItem&&<FleetHistoryModal item={historyItem} data={history} loading={historyLoading} close={()=>{setHistoryItem(null);setHistory(null);}}/>}
  </div>;
}

function FleetMetric({icon,label,value,tone}:{icon:string;label:string;value:number;tone:string}){return <article className={`fleet-metric ${tone}`}><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></article>;}

function FleetSettings({settings,close,saved}:{settings:FleetResponse["settings"];close:()=>void;saved:(message:string)=>void}){
  const [values,setValues]=useState(settings);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const result=await api<{message:string}>("/api/fleet-status",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});saved(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível salvar.");}finally{setBusy(false);}};
  return <form className="fleet-settings" onSubmit={submit}><div><strong>Limites de destaque do tempo parado</strong><span>Os cartões mudam de prioridade conforme estas faixas.</span></div><label>Atenção após<input type="number" min="1" step="0.5" value={values.attentionHours} onChange={(e)=>setValues({...values,attentionHours:Number(e.target.value)})}/><small>horas</small></label><label>Alto após<input type="number" min="1" step="0.5" value={values.highHours} onChange={(e)=>setValues({...values,highHours:Number(e.target.value)})}/><small>horas</small></label><label>Crítico após<input type="number" min="1" step="0.5" value={values.criticalHours} onChange={(e)=>setValues({...values,criticalHours:Number(e.target.value)})}/><small>horas</small></label>{error&&<em>{error}</em>}<button type="button" onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?"Salvando...":"Salvar limites"}</button></form>;
}

function UpdateFleetModal({item,mechanics,close,saved}:{item:FleetItem;mechanics:string[];close:()=>void;saved:(message:string)=>void}){
  const [status,setStatus]=useState<FleetStatus>(item.status);const [occurredAt,setOccurredAt]=useState(localDateTime());const [reason,setReason]=useState(item.reason??"");const [problem,setProblem]=useState(item.problemDescription??"");const [service,setService]=useState(item.serviceDescription??"");const [servicePerformed,setServicePerformed]=useState(item.servicePerformed??"");const [location,setLocation]=useState(item.location??item.front);const [notes,setNotes]=useState("");const [parts,setParts]=useState("");const [selectedMechanics,setSelectedMechanics]=useState<string[]>(item.mechanics);const [newMechanic,setNewMechanic]=useState("");
  const [orders,setOrders]=useState<DraftOrder[]>(item.orders.map((order)=>({...order,clientId:order.id??crypto.randomUUID()})));const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const addMechanic=()=>{const name=newMechanic.trim();if(name&&!selectedMechanics.includes(name))setSelectedMechanics([...selectedMechanics,name]);setNewMechanic("");};
  const addOrder=()=>setOrders([...orders,{clientId:crypto.randomUUID(),orderNumber:"",requestedAt:localDay(),description:"",quantity:null,unit:"UN",requester:"",supplier:"",status:"REQUESTED",notes:""}]);
  const patchOrder=(clientId:string,patch:Partial<DraftOrder>)=>setOrders(orders.map((order)=>order.clientId===clientId?{...order,...patch}:order));
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError("");try{const result=await api<{message:string}>("/api/fleet-status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({equipmentId:item.id,status,occurredAt:datetimeIso(occurredAt),reason,problemDescription:problem,serviceDescription:service,servicePerformed,location,notes,partsUsed:parts,mechanics:selectedMechanics,orders:orders.map((order)=>({id:order.id,orderNumber:order.orderNumber,requestedAt:order.requestedAt,description:order.description,quantity:order.quantity,unit:order.unit,requester:order.requester,supplier:order.supplier,status:order.status,notes:order.notes}))})});saved(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível atualizar o status.");}finally{setBusy(false);}};
  const needsProblem=status==="STOPPED";const needsMaintenance=status==="MAINTENANCE";const needsClosing=status==="READY"||(status==="OPERATING"&&Boolean(item.occurrenceId));const showOrders=Boolean(item.occurrenceId)||status==="WAITING_PART"||status==="WAITING_ORDER";
  return <div className="fleet-modal-backdrop" role="presentation"><form className="fleet-modal" onSubmit={submit}><header><div><p>ATUALIZAÇÃO OPERACIONAL</p><h2>{item.prefix} · {item.model}</h2><span>{item.category} · {item.front}</span></div><button type="button" onClick={close} aria-label="Fechar">×</button></header><div className="fleet-modal-body">
    <div className="fleet-current-banner"><span>Status anterior</span><b className={`fleet-status ${tone(item.status)}`}>{item.statusLabel}</b><small>Ocorrência {item.occurrenceId??"será criada automaticamente"}</small></div>
    <div className="fleet-form-grid"><label>Novo status *<select value={status} onChange={(event)=>setStatus(event.target.value as FleetStatus)}>{statusOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Data e hora *<input type="datetime-local" value={occurredAt} onChange={(event)=>setOccurredAt(event.target.value)} required/></label><label>Local / Frente<input value={location} onChange={(event)=>setLocation(event.target.value)}/></label></div>
    {(needsProblem||status!=="OPERATING")&&<section className="fleet-form-section"><h3>Motivo e problema</h3><div className="fleet-form-grid"><label>Motivo {needsProblem&&"*"}<input value={reason} onChange={(event)=>setReason(event.target.value)} required={needsProblem} placeholder="Ex.: Vazamento de óleo hidráulico"/></label><label className="span-2">Descrição do problema {needsProblem&&"*"}<textarea value={problem} onChange={(event)=>setProblem(event.target.value)} required={needsProblem} placeholder="Descreva o defeito identificado."/></label></div></section>}
    {(needsMaintenance||status==="WAITING_MECHANIC"||status==="WAITING_PART"||status==="WAITING_ORDER"||status==="WAITING_EXTERNAL_SERVICE")&&<section className="fleet-form-section"><h3>Manutenção e responsáveis</h3><label>Serviço sendo executado {needsMaintenance&&"*"}<textarea value={service} onChange={(event)=>setService(event.target.value)} required={needsMaintenance} placeholder="Ex.: Substituição da mangueira hidráulica do implemento"/></label><div className="mechanic-picker"><span>Selecionar mecânicos {needsMaintenance&&"*"}</span><div>{[...new Set([...mechanics,...selectedMechanics])].map((name)=><label key={name}><input type="checkbox" checked={selectedMechanics.includes(name)} onChange={(event)=>setSelectedMechanics(event.target.checked?[...selectedMechanics,name]:selectedMechanics.filter((value)=>value!==name))}/>{name}</label>)}</div><div className="new-mechanic"><input value={newMechanic} onChange={(event)=>setNewMechanic(event.target.value)} placeholder="Cadastrar/usar outro mecânico"/><button type="button" onClick={addMechanic}>Adicionar</button></div></div></section>}
    {needsClosing&&<section className="fleet-form-section closing"><h3>Encerramento da ocorrência</h3><label>Serviço realizado / O que foi feito *<textarea value={servicePerformed} onChange={(event)=>setServicePerformed(event.target.value)} required placeholder="Descreva a solução executada, testes e resultado."/></label><label>Peças utilizadas<textarea value={parts} onChange={(event)=>setParts(event.target.value)} placeholder="Peças e materiais aplicados."/></label></section>}
    {showOrders&&<section className="fleet-form-section"><div className="fleet-section-title"><h3>Pedidos / Peças pendentes</h3><button type="button" onClick={addOrder}>＋ ADICIONAR PEDIDO</button></div>{orders.map((order,index)=><div className="fleet-order-editor" key={order.clientId}><header><b>Pedido {index+1}</b><button type="button" onClick={()=>setOrders(orders.filter((value)=>value.clientId!==order.clientId))}>Remover</button></header><div className="fleet-form-grid"><label>Número do pedido *<input value={order.orderNumber} onChange={(e)=>patchOrder(order.clientId,{orderNumber:e.target.value})}/></label><label>Data do pedido *<input type="date" value={order.requestedAt.slice(0,10)} onChange={(e)=>patchOrder(order.clientId,{requestedAt:e.target.value})}/></label><label>Status<select value={order.status} onChange={(e)=>patchOrder(order.clientId,{status:e.target.value as OrderStatus})}>{orderOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="span-2">Descrição da peça/material *<input value={order.description} onChange={(e)=>patchOrder(order.clientId,{description:e.target.value})}/></label><label>Quantidade<input type="number" min="0.01" step="0.01" value={order.quantity??""} onChange={(e)=>patchOrder(order.clientId,{quantity:e.target.value?Number(e.target.value):null})}/></label><label>Unidade<input value={order.unit??""} onChange={(e)=>patchOrder(order.clientId,{unit:e.target.value})}/></label><label>Solicitante<input value={order.requester??""} onChange={(e)=>patchOrder(order.clientId,{requester:e.target.value})}/></label><label>Fornecedor<input value={order.supplier??""} onChange={(e)=>patchOrder(order.clientId,{supplier:e.target.value})}/></label></div></div>)}</section>}
    <label className="fleet-notes">Observações<textarea value={notes} onChange={(event)=>setNotes(event.target.value)} placeholder="Informações adicionais desta movimentação."/></label>{error&&<div className="fleet-form-error">! {error}</div>}
  </div><footer><button type="button" onClick={close}>Cancelar</button><button className="primary" disabled={busy}>{busy?"SALVANDO...":"SALVAR ATUALIZAÇÃO"}</button></footer></form></div>;
}

function FleetHistoryModal({item,data,loading,close}:{item:FleetItem;data:HistoryData|null;loading:boolean;close:()=>void}){
  return <div className="fleet-modal-backdrop"><section className="fleet-modal fleet-history-modal"><header><div><p>HISTÓRICO COMPLETO DE STATUS</p><h2>{item.prefix} · {item.model}</h2><span>{item.category} · {item.front}</span></div><button onClick={close}>×</button></header><div className="fleet-modal-body">{loading&&<div className="fleet-history-loading">Carregando ocorrências...</div>}{data?.occurrences.map((occurrence)=><article className="fleet-occurrence" key={occurrence.id}><header><div><b>{occurrence.id}</b><span>Parou em {formatDate(occurrence.startedAt)}</span></div><div><small>Conclusão</small><b>{formatDate(occurrence.endedAt)}</b></div><div><small>Retorno à operação</small><b>{formatDate(occurrence.returnedToOperationAt)}</b></div></header><div className="fleet-occurrence-summary"><p><small>MOTIVO</small><b>{occurrence.reason??occurrence.problemDescription??"Não informado"}</b></p><p><small>O QUE FOI FEITO</small><b>{occurrence.servicePerformed??"Ocorrência em andamento"}</b></p></div><div className="fleet-history-timeline">{occurrence.events.slice().reverse().map((event)=><div key={event.id}><time>{formatDate(event.occurredAt)}</time><i className={tone(event.status)}/><p><b>{event.statusLabel}</b><span>{event.reason??event.serviceDescription??event.servicePerformed??"Atualização de status"}</span><small>{event.mechanics.length?`Mecânico(s): ${event.mechanics.join(", ")} · `:""}{event.updatedBy}</small></p></div>)}</div>{occurrence.orders.length>0&&<div className="fleet-history-orders"><strong>PEDIDOS RELACIONADOS</strong>{occurrence.orders.map((order)=><span key={order.id}>{order.orderNumber} — {order.description} — {order.statusLabel}</span>)}</div>}</article>)}{data&&!data.occurrences.length&&<div className="fleet-empty"><strong>Nenhuma ocorrência registrada</strong><small>As próximas mudanças ficarão preservadas nesta linha do tempo.</small></div>}</div><footer><button className="primary" onClick={close}>Fechar histórico</button></footer></section></div>;
}
