"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import {useCallback,useEffect,useState,type FormEvent} from "react";

type Level="WARNING"|"NEAR"|"OVERDUE";
type Recipient={id:number;name:string;phone:string;active:boolean;categories:string[];alertTypes:Level[];createdAt:string;updatedAt:string};
type Delivery={id:number;equipmentPrefix:string;category:string;maintenanceName:string;alertStatus:string;current_value:number|null;next_value:number|null;remaining_value:number|null;unit:"HOURS"|"KM"|null;recipientName:string;recipientPhone:string;message:string;result:string;resultLabel:string;providerMessageId:string|null;errorReason:string|null;triggerType:string;createdAt:string};
type Connection={name:string;senderPhone:string;phoneNumberId:string;wabaId:string;apiVersion:string;status:"NOT_CONFIGURED"|"CONNECTED"|"ERROR";lastError:string;lastTestedAt:string;maskedAccessToken:string;hasAccessToken:boolean;encryptionReady:boolean};
type Configuration={provider:string;configured:boolean;connected:boolean;requirements:{accessToken:boolean;phoneNumberId:boolean;wabaId:boolean;approvedTemplate:boolean;schedulerSecret:boolean;webhookVerifyToken:boolean;appSecret:boolean};settings:{sendMode:"MANUAL"|"API";automaticEnabled:boolean;overdueRepeatDays:number;templateName:string;templateLanguage:string};connection:Connection};
type WhatsappData={configuration:Configuration;recipients:Recipient[];deliveries:Delivery[];categories:string[];alertTypes:Level[]};
type Props={authUser:{permissions:string[]};flash:(message:string)=>void};

async function requestJson<T>(url:string,options?:RequestInit){const response=await fetch(url,{cache:"no-store",...options});const data=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok)throw new Error(String(data.error??"Não foi possível concluir a operação."));return data as T;}
const levelLabels:Record<Level,string>={WARNING:"Próximas trocas",NEAR:"Urgentes",OVERDUE:"Vencidas"};
const triggerLabels:Record<string,string>={AUTOMATIC:"Automático",MANUAL:"Manual",TEST:"Teste",OVERDUE_REPEAT:"Lembrete vencido"};
function dateTime(value:string){const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(date);}
function number(value:number|null|undefined){return value===null||value===undefined?"—":value.toLocaleString("pt-BR",{maximumFractionDigits:1});}
function deliveryBalance(item:Delivery){const overdue=item.alertStatus==="NEAR"||item.alertStatus==="OVERDUE";return `${overdue?item.alertStatus==="NEAR"?"Urgente — vencido há":"Vencido há":"Restam"}: ${number(overdue?Math.abs(item.remaining_value??0):item.remaining_value)}`;}

export default function WhatsappView({authUser,flash}:Props){
  const [data,setData]=useState<WhatsappData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [tab,setTab]=useState<"settings"|"history">("settings");const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<Recipient|null>(null);const [testRecipient,setTestRecipient]=useState(0);const [connectionOpen,setConnectionOpen]=useState(false);const [sendMode,setSendMode]=useState<"MANUAL"|"API">("MANUAL");
  const manage=authUser.permissions.includes("whatsapp.manage");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const next=await requestJson<WhatsappData>("/api/whatsapp");setData(next);setSendMode(next.configuration.settings.sendMode);setTestRecipient((current)=>current||next.recipients.find((item)=>item.active)?.id||0);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível carregar o WhatsApp.");}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);

  async function saveConnection(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);try{const result=await requestJson<{message:string}>("/api/whatsapp",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"UPDATE_CONNECTION",connectionName:form.get("connectionName"),senderPhone:form.get("senderPhone"),phoneNumberId:form.get("phoneNumberId"),wabaId:form.get("wabaId"),accessToken:form.get("accessToken"),apiVersion:form.get("apiVersion")})});await load();flash(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível salvar a conexão.");}finally{setBusy(false);}}
  async function testConnection(){setBusy(true);setError("");try{const result=await requestJson<{message:string}>("/api/whatsapp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TEST_CONNECTION"})});await load();flash(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"A validação com a Meta falhou.");await load();}finally{setBusy(false);}}
  async function saveSettings(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data)return;setBusy(true);const form=new FormData(event.currentTarget);try{const result=await requestJson<{message:string}>("/api/whatsapp",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"UPDATE_SETTINGS",sendMode:form.get("sendMode"),automaticEnabled:form.get("automaticEnabled")==="on",overdueRepeatDays:Number(form.get("overdueRepeatDays")),templateName:form.get("templateName"),templateLanguage:form.get("templateLanguage")})});await load();flash(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível salvar.");}finally{setBusy(false);}}
  async function saveRecipient(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!data)return;setBusy(true);const form=new FormData(event.currentTarget);const categories=data.categories.filter((item)=>form.get(`category-${item}`)==="on");const alertTypes=data.alertTypes.filter((item)=>form.get(`level-${item}`)==="on");try{const result=await requestJson<{message:string}>("/api/whatsapp",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:editing?"UPDATE_RECIPIENT":"CREATE_RECIPIENT",id:editing?.id,name:form.get("name"),phone:form.get("phone"),active:form.get("active")==="on",categories:form.get("allCategories")==="on"?["ALL"]:categories,alertTypes})});setEditing(null);event.currentTarget.reset();await load();flash(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível salvar o destinatário.");}finally{setBusy(false);}}
  async function removeRecipient(item:Recipient){if(!window.confirm(`Excluir ${item.name} dos alertas do WhatsApp?\n\nO histórico de envios será preservado.`))return;setBusy(true);try{const result=await requestJson<{message:string}>("/api/whatsapp",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.id})});await load();flash(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"Não foi possível excluir.");}finally{setBusy(false);}}
  async function sendTest(){if(!testRecipient||!data?.configuration.connected)return;const item=data.recipients.find((recipient)=>recipient.id===testRecipient);if(!window.confirm(`Enviar mensagem de teste para ${item?.name??"o destinatário selecionado"}?`))return;setBusy(true);try{const result=await requestJson<{message:string}>("/api/whatsapp",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"TEST",recipientId:testRecipient})});await load();flash(result.message);}catch(problem){setError(problem instanceof Error?problem.message:"O teste falhou.");await load();}finally{setBusy(false);}}

  if(loading&&!data)return <div className="page-loading"><span/><p>Carregando integração do WhatsApp...</p></div>;
  if(!data)return <div className="operation-error"><span>!</span><div><strong>Falha ao carregar o WhatsApp</strong><p>{error}</p></div><button onClick={load}>Tentar novamente</button></div>;
  const config=data.configuration;const connection=config.connection;const connectionStatusLabel=connection.status==="CONNECTED"?"CONECTADO":connection.status==="ERROR"?"ERRO NA CONEXÃO":"NÃO CONFIGURADO";const statusLabel=config.settings.sendMode==="MANUAL"?"MODO MANUAL":connectionStatusLabel;

  return <>
    <div className="page-heading module-heading"><div><p className="eyebrow">COMUNICAÇÃO AUTOMÁTICA</p><h1>Alertas pelo WhatsApp</h1><span>Conexão oficial, destinatários e rastreabilidade integrados à Central de Alertas.</span></div><div className="heading-actions"><span className={`wa-health ${config.connected?"ready":"missing"}`}>{statusLabel}</span></div></div>
    <div className="wa-tabs"><button className={tab==="settings"?"active":""} onClick={()=>setTab("settings")}>Configurações e destinatários</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>Histórico de envios <b>{data.deliveries.length}</b></button></div>
    {error&&<div className="operation-error compact"><span>!</span><div><strong>Atenção</strong><p>{error}</p></div><button onClick={()=>setError("")}>×</button></div>}
    {tab==="settings"?<div className="wa-settings-grid">
      <article className="panel wa-config-card wa-connection-card">
        <div className="panel-head"><div><h2>CONEXÃO COM WHATSAPP</h2><p>{config.provider}</p></div><span className={`live-data-badge ${config.connected?"ok":""}`}>{connectionStatusLabel}</span></div>
        {config.connected?<div className="wa-ready-box"><strong>Integração validada</strong><span>Remetente: {connection.senderPhone||"Não informado"}</span><small>Último teste: {connection.lastTestedAt?dateTime(connection.lastTestedAt):"—"}</small></div>:<div className="wa-missing-box"><strong>WHATSAPP NÃO CONFIGURADO</strong><span>Envio não realizado: integração WhatsApp não configurada.</span><small>Cadastre os dados reais da Meta e execute o teste de conexão. Sem isso, o sistema não tenta envios automáticos nem cria falhas repetidas.</small></div>}
        {connection.lastError&&<div className="wa-api-error"><strong>Último erro real da integração</strong><span>{connection.lastError}</span></div>}
        <div className="wa-connection-actions"><button className="primary" disabled={!manage} onClick={()=>setConnectionOpen(!connectionOpen)}>{connectionOpen?"FECHAR CONFIGURAÇÃO":"CONECTAR / CONFIGURAR WHATSAPP"}</button><button className="secondary" disabled={!manage||busy||!connection.hasAccessToken||!connection.phoneNumberId||!connection.wabaId} onClick={testConnection}>{busy?"Validando...":"Testar conexão real"}</button></div>
        {connectionOpen&&<form className="wa-form wa-connection-form" onSubmit={saveConnection}>
          <div className="wa-field-row"><label>Nome da conexão<input name="connectionName" required defaultValue={connection.name} placeholder="Ex.: Manutenção Preventiva"/></label><label>Número remetente<input name="senderPhone" required defaultValue={connection.senderPhone} inputMode="numeric" placeholder="5591999999999"/><small>Formato: 55 + DDD + número, somente dígitos.</small></label></div>
          <div className="wa-field-row"><label>Phone Number ID<input name="phoneNumberId" required defaultValue={connection.phoneNumberId} inputMode="numeric"/></label><label>WABA ID<input name="wabaId" required defaultValue={connection.wabaId} inputMode="numeric"/></label></div>
          <div className="wa-field-row"><label>Access Token<input name="accessToken" type="password" autoComplete="new-password" placeholder={connection.hasAccessToken?"Deixe vazio para manter o token protegido":"Cole o token real da Meta"}/>{connection.maskedAccessToken&&<small>Atual: {connection.maskedAccessToken}</small>}</label><label>Versão da API<input name="apiVersion" required defaultValue={connection.apiVersion||"v23.0"} placeholder="v23.0"/></label></div>
          <div className="wa-security-note"><span>🔒</span><p>O token nunca é devolvido completo ao navegador. Ele é criptografado no backend antes de ser gravado no banco.</p></div>
          {!connection.encryptionReady&&<div className="wa-missing-box"><strong>Proteção do token pendente</strong><span>Configure <code>WHATSAPP_CREDENTIALS_ENCRYPTION_KEY</code> no backend para permitir o salvamento seguro do Access Token.</span></div>}
          <button className="primary" disabled={!manage||busy}>{busy?"Salvando...":"Salvar dados da conexão"}</button>
        </form>}
      </article>

      <article className="panel wa-automation-card"><div className="panel-head"><div><h2>Modo de envio e automação</h2><p>O modo manual não utiliza token e preserva toda a configuração da API.</p></div><span className={`live-data-badge ${config.configured?"ok":""}`}>{sendMode}</span></div><form className="wa-form" onSubmit={saveSettings}><fieldset className="wa-send-mode"><legend>MODO DE ENVIO</legend><label className={sendMode==="MANUAL"?"selected":""}><input name="sendMode" type="radio" value="MANUAL" checked={sendMode==="MANUAL"} onChange={()=>setSendMode("MANUAL")}/><span><strong>Manual</strong><small>Abre o WhatsApp com a mensagem pronta; você confirma o envio.</small></span></label><label className={sendMode==="API"?"selected":""}><input name="sendMode" type="radio" value="API" checked={sendMode==="API"} onChange={()=>setSendMode("API")}/><span><strong>API</strong><small>Envia pela WhatsApp Cloud API quando a integração estiver concluída.</small></span></label></fieldset><label className="wa-switch"><input name="automaticEnabled" type="checkbox" defaultChecked={config.settings.automaticEnabled} disabled={sendMode==="MANUAL"}/><span/><div><strong>Alertas automáticos</strong><small>{sendMode==="MANUAL"?"Desativados no modo manual.":"Envia somente em mudança de status e com conexão pronta."}</small></div></label><div className="wa-field-row"><label>Modelo aprovado pela Meta<input name="templateName" defaultValue={config.settings.templateName} placeholder="maintenance_alert_ptbr"/></label><label>Idioma do modelo<input name="templateLanguage" defaultValue={config.settings.templateLanguage}/></label></div><label>Repetir manutenção vencida<select name="overdueRepeatDays" defaultValue={config.settings.overdueRepeatDays}><option value="0">Não repetir</option><option value="1">A cada 1 dia</option><option value="2">A cada 2 dias</option><option value="3">A cada 3 dias</option><option value="7">A cada 7 dias</option></select></label><div className="wa-requirements"><span className={config.connected?"ok":""}><i>{config.connected?"✓":"!"}</i> Conexão validada</span><span className={config.requirements.approvedTemplate?"ok":""}><i>{config.requirements.approvedTemplate?"✓":"!"}</i> Modelo aprovado</span><span className={config.requirements.schedulerSecret?"ok":""}><i>{config.requirements.schedulerSecret?"✓":"!"}</i> Segredo do agendador</span><span className={config.requirements.webhookVerifyToken?"ok":""}><i>{config.requirements.webhookVerifyToken?"✓":"!"}</i> Token do webhook</span></div><button className="primary" disabled={!manage||busy}>{busy?"Salvando...":"Salvar modo e automação"}</button></form></article>

      <article className="panel wa-recipient-form"><div className="panel-head"><div><h2>{editing?"Editar destinatário":"Novo destinatário"}</h2><p>Remetente e destinatários são configurações separadas.</p></div>{editing&&<button className="secondary small" onClick={()=>setEditing(null)}>Cancelar edição</button>}</div><form className="wa-form" onSubmit={saveRecipient} key={editing?.id??"new"}><div className="wa-field-row"><label>Nome<input name="name" required defaultValue={editing?.name}/></label><label>Número de WhatsApp<input name="phone" required defaultValue={editing?.phone} inputMode="numeric" placeholder="5591999999999"/><small>55 + DDD + número, sem espaços ou símbolos.</small></label></div><label className="wa-switch"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/><span/><div><strong>Destinatário ativo</strong><small>Somente ativos recebem notificações.</small></div></label><fieldset><legend>Categorias</legend><label className="wa-check"><input name="allCategories" type="checkbox" defaultChecked={editing?.categories.includes("ALL")??true}/><span>Todas as categorias</span></label><div className="wa-check-grid">{data.categories.map((category)=><label className="wa-check" key={category}><input name={`category-${category}`} type="checkbox" defaultChecked={editing?.categories.includes(category)??false}/><span>{category}</span></label>)}</div></fieldset><fieldset><legend>Tipos de alerta</legend><div className="wa-check-grid levels">{data.alertTypes.map((level)=><label className="wa-check" key={level}><input name={`level-${level}`} type="checkbox" defaultChecked={editing?.alertTypes.includes(level)??true}/><span>{levelLabels[level]}</span></label>)}</div></fieldset><button className="primary" disabled={!manage||busy}>{busy?"Salvando...":editing?"Atualizar destinatário":"Cadastrar destinatário"}</button></form></article>

      <article className="panel wa-recipient-list"><div className="panel-head"><div><h2>Destinatários cadastrados</h2><p>{data.recipients.length} registro(s)</p></div></div>{data.recipients.map((item)=><div className="wa-recipient-row" key={item.id}><span className="wa-avatar">{item.name.split(/\s+/).slice(0,2).map((part)=>part[0]).join("")}</span><div><strong>{item.name}</strong><small>{item.phone}</small><p>{item.categories.includes("ALL")?"Todas as categorias":item.categories.join(", ")} · {item.alertTypes.map((level)=>levelLabels[level]).join(", ")}</p></div><span className={`status-pill ${item.active?"green":"gray"}`}>{item.active?"Ativo":"Inativo"}</span>{manage&&<div className="wa-row-actions"><button onClick={()=>setEditing(item)}>Editar</button><button className="danger-action" disabled={busy} onClick={()=>removeRecipient(item)}>Excluir</button></div>}</div>)}{!data.recipients.length&&<div className="empty-state">Nenhum destinatário cadastrado.</div>}<div className="wa-test-box"><div><strong>ENVIAR MENSAGEM DE TESTE</strong><small>Disponível somente após a conexão ser validada.</small></div><select value={testRecipient} onChange={(event)=>setTestRecipient(Number(event.target.value))}><option value="0">Selecione</option>{data.recipients.filter((item)=>item.active).map((item)=><option key={item.id} value={item.id}>{item.name} · {item.phone}</option>)}</select><button className="primary" disabled={!manage||busy||!testRecipient||!config.connected} onClick={sendTest}>Enviar teste</button></div></article>
    </div>:<article className="panel module-panel wa-history"><div className="panel-head"><div><h2>HISTÓRICO DE ALERTAS WHATSAPP</h2><p>Cada tentativa, resposta da Meta e motivo de erro ficam registrados.</p></div><span className="live-data-badge">{data.deliveries.length} REGISTROS</span></div><div className="table-scroll"><table><thead><tr><th>Data / Hora</th><th>Equipamento</th><th>Manutenção</th><th>Status</th><th>Leitura / Próxima</th><th>Destinatário</th><th>Disparo</th><th>Resultado</th><th>Mensagem / API</th></tr></thead><tbody>{data.deliveries.map((item)=><tr key={item.id}><td>{dateTime(item.createdAt)}</td><td><strong>{item.equipmentPrefix}</strong><small>{item.category}</small></td><td>{item.maintenanceName}</td><td>{item.alertStatus}</td><td>{number(item.current_value)} / {number(item.next_value)} {item.unit==="KM"?"km":"h"}<small>{deliveryBalance(item)} {item.unit==="KM"?"km":"h"}</small></td><td>{item.recipientName}<small>{item.recipientPhone}</small></td><td>{triggerLabels[item.triggerType]??item.triggerType}</td><td><span className={`wa-result ${item.result.toLowerCase()}`}>{item.resultLabel}</span></td><td><details><summary>Ver detalhes</summary><p>{item.message}</p>{item.providerMessageId&&<small>ID Meta: {item.providerMessageId}</small>}{item.errorReason&&<small>Erro real: {item.errorReason}</small>}</details></td></tr>)}</tbody></table></div>{!data.deliveries.length&&<div className="empty-state">Nenhuma tentativa de envio registrada.</div>}</article>}
  </>;
}
